version: '3.8'

services:
  # Задание 1: HTTP сервер
  swoole-http:
    build: .
    container_name: swoole-http-server
    ports:
      - "9501:9501"
    volumes:
      - ./task1:/app
    command: php http_server.php
    restart: unless-stopped

  # Задание 2: Таймер сервер
  swoole-timer:
    build: .
    container_name: swoole-timer-server
    volumes:
      - ./task2:/app
    command: php timer_server.php
    restart: unless-stopped
    tty: true
    stdin_open: true